#!/usr/bin/env python3
"""
Preflight-конфигуратор перед запуском Agent Navigator Pro.

Режимы:
- default: безопасные значения по умолчанию
- adaptive: автонастройка по железу (HardwareProfiler + TierSelector)
- manual: интерактивный выбор tier и ключевых лимитов

Результат сохраняется в backend/.env.runtime.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = PROJECT_ROOT / "backend"
RUNTIME_ENV = BACKEND_DIR / ".env.runtime"


sys.path.insert(0, str(BACKEND_DIR))



@dataclass
class RuntimeProfile:
    mode: str
    tier: int
    llm_ctx_size: int
    retrieval_top_k: int
    rag_mode: str
    max_concurrent_llm: int
    effective_context_tokens: int
    rag_context_ratio: float

    def to_env(self) -> Dict[str, str]:
        return {
            "RUNTIME_PROFILE_MODE": self.mode,
            "TIER_OVERRIDE": str(self.tier),
            "CONTEXT_SIZE_QWEN14B": str(self.llm_ctx_size),
            "RAG_RETRIEVAL_TOP_K": str(self.retrieval_top_k),
            "RAG_MODE_OVERRIDE": self.rag_mode,
            "MAX_CONCURRENT_LLM": str(self.max_concurrent_llm),
            "EFFECTIVE_CONTEXT_TOKENS": str(self.effective_context_tokens),
            "RAG_CONTEXT_RATIO": f"{self.rag_context_ratio:.2f}",
        }


def _effective_context_tokens(ctx_size: int, parallel_slots: int, hard_cap: int) -> int:
    slots = max(1, parallel_slots)
    per_request = ctx_size // slots
    return max(1024, min(per_request, hard_cap))


def _build_profile(mode: str, tier: int, llm_ctx_size: int, retrieval_top_k: int, rag_mode: str,
                   max_concurrent_llm: int, parallel_slots: int, hard_cap: int,
                   rag_context_ratio: float) -> RuntimeProfile:
    effective_ctx = _effective_context_tokens(llm_ctx_size, parallel_slots, hard_cap)
    return RuntimeProfile(
        mode=mode,
        tier=int(tier),
        llm_ctx_size=llm_ctx_size,
        retrieval_top_k=retrieval_top_k,
        rag_mode=rag_mode,
        max_concurrent_llm=max_concurrent_llm,
        effective_context_tokens=effective_ctx,
        rag_context_ratio=rag_context_ratio,
    )


def _default_profile(parallel_slots: int, hard_cap: int) -> RuntimeProfile:
    return _build_profile(
        mode="default",
        tier=2,
        llm_ctx_size=8192,
        retrieval_top_k=7,
        rag_mode="corrective",
        max_concurrent_llm=1,
        parallel_slots=parallel_slots,
        hard_cap=hard_cap,
        rag_context_ratio=0.60,
    )


def _adaptive_profile(parallel_slots: int, hard_cap: int) -> RuntimeProfile:
    try:
        from services.hardware import HardwareProfiler, TierSelector
    except Exception as exc:
        print(f"[WARN] Hardware profiler недоступен ({exc}), fallback на default-профиль")
        return _default_profile(parallel_slots=parallel_slots, hard_cap=hard_cap)

    profiler = HardwareProfiler()
    selector = TierSelector()
    profile = profiler.detect()
    tier_cfg = selector.select(profile)
    return _build_profile(
        mode="adaptive",
        tier=tier_cfg.tier,
        llm_ctx_size=tier_cfg.llm_ctx_size,
        retrieval_top_k=tier_cfg.retrieval_top_k,
        rag_mode=tier_cfg.rag_mode,
        max_concurrent_llm=tier_cfg.max_concurrent_llm,
        parallel_slots=parallel_slots,
        hard_cap=hard_cap,
        rag_context_ratio=0.60,
    )


def _manual_profile(parallel_slots: int, hard_cap: int) -> RuntimeProfile:
    print("\nВыберите tier:")
    print("  1) lite (tier1)")
    print("  2) balanced (tier2)")
    print("  3) max-quality (tier3)")
    raw = input("Номер [2]: ").strip() or "2"
    tier_map = {"1": 1, "2": 2, "3": 3}
    tier = tier_map.get(raw, 2)

    defaults = {
        1: (4096, 5, "simple", 1),
        2: (8192, 7, "corrective", 1),
        3: (16384, 10, "agentic", 1),
    }
    def_ctx, def_top_k, def_rag_mode, def_concurrency = defaults[tier]

    llm_ctx_size = int((input(f"llm ctx size [{def_ctx}]: ").strip() or str(def_ctx)))
    retrieval_top_k = int((input(f"retrieval top_k [{def_top_k}]: ").strip() or str(def_top_k)))
    max_concurrent_llm = int((input(f"max concurrent llm [{def_concurrency}]: ").strip() or str(def_concurrency)))

    return _build_profile(
        mode="manual",
        tier=tier,
        llm_ctx_size=llm_ctx_size,
        retrieval_top_k=retrieval_top_k,
        rag_mode=def_rag_mode,
        max_concurrent_llm=max_concurrent_llm,
        parallel_slots=parallel_slots,
        hard_cap=hard_cap,
        rag_context_ratio=0.60,
    )


def _save_env(profile: RuntimeProfile, output_path: Path) -> None:
    header = "# Auto-generated by scripts/preflight.py\n"
    lines = [f"{k}={v}" for k, v in profile.to_env().items()]
    output_path.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Preflight runtime profile configurator")
    parser.add_argument("--mode", choices=["default", "adaptive", "manual"], default="adaptive")
    parser.add_argument("--parallel-slots", type=int, default=int(os.getenv("LLAMA_PARALLEL_SLOTS", "1")))
    parser.add_argument("--hard-cap", type=int, default=int(os.getenv("RUNTIME_CONTEXT_HARD_CAP", "16384")))
    parser.add_argument("--output", default=str(RUNTIME_ENV))
    args = parser.parse_args()

    if args.mode == "default":
        profile = _default_profile(parallel_slots=args.parallel_slots, hard_cap=args.hard_cap)
    elif args.mode == "manual":
        profile = _manual_profile(parallel_slots=args.parallel_slots, hard_cap=args.hard_cap)
    else:
        profile = _adaptive_profile(parallel_slots=args.parallel_slots, hard_cap=args.hard_cap)

    output_path = Path(args.output).resolve()
    _save_env(profile, output_path)

    print("\n=== Runtime profile generated ===")
    for key, value in profile.to_env().items():
        print(f"{key}={value}")
    print(f"\nSaved to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

